step_up:
  name: Step Up
  description: Increase brightness by one step along the magic curve
  icon: mdi:brightness-5
  fields:
    area_id:
      name: Area
      description: The area(s) to control
      required: true
      example: ["living_room", "kitchen"]
      selector:
        area:
          multiple: true

step_down:
  name: Step Down
  description: Decrease brightness by one step along the magic curve
  icon: mdi:brightness-4
  fields:
    area_id:
      name: Area
      description: The area(s) to control
      required: true
      example: ["living_room", "kitchen"]
      selector:
        area:
          multiple: true

dim_up:
  name: Dim Up
  description: Raise the brightness curve without changing MagicLight color
  icon: mdi:brightness-7
  fields:
    area_id:
      name: Area
      description: The area(s) to brighten
      required: true
      example: ["living_room", "kitchen"]
      selector:
        area:
          multiple: true

dim_down:
  name: Dim Down
  description: Lower the brightness curve without changing MagicLight color
  icon: mdi:brightness-3
  fields:
    area_id:
      name: Area
      description: The area(s) to dim
      required: true
      example: ["living_room", "kitchen"]
      selector:
        area:
          multiple: true

reset:
  name: Reset
  description: Turn on lights to magic value of current time, enable MagicLight
  icon: mdi:restore
  fields:
    area_id:
      name: Area
      description: The area(s) to reset
      required: true
      example: ["living_room", "kitchen"]
      selector:
        area:
          multiple: true

magiclight_on:
  name: MagicLight On
  description: Turn on lights and enable MagicLight mode for an area
  icon: mdi:lightbulb-on
  fields:
    area_id:
      name: Area
      description: The area(s) to enable MagicLight for
      required: true
      example: ["living_room", "kitchen"]
      selector:
        area:
          multiple: true

magiclight_off:
  name: MagicLight Off
  description: Disable MagicLight mode for an area (lights remain unchanged)
  icon: mdi:lightbulb-off
  fields:
    area_id:
      name: Area
      description: The area(s) to disable MagicLight for
      required: true
      example: ["living_room", "kitchen"]
      selector:
        area:
          multiple: true

magiclight_toggle:
  name: MagicLight Toggle
  description: Smart toggle - turns on lights with MagicLight if off, turns off lights and disables MagicLight if on
  icon: mdi:lightbulb-auto
  fields:
    area_id:
      name: Area
      description: The area(s) to toggle
      required: true
      example: ["living_room", "kitchen"]
      selector:
        area:
          multiple: true
