# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: MagicLight
version: "3.2.1"
slug: magiclight
description: Connects to Home Assistant WebSocket API and listens for switch events
url: "https://github.com/dtconceptsnc/magiclight"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
auth_api: true
homeassistant_api: true
ingress: true
ingress_port: 8099
ingress_entry: /
panel_icon: mdi:lightbulb
panel_title: MagicLight
panel_admin: false
options:
  color_mode: "kelvin"
schema:
  color_mode: list(kelvin|rgb|xy)
